version: '3'

services:
  app:
    build: .
    command: "yarn dev"
    env_file: .env
    environment:
      PG_HOST: pg
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - pg
    networks:
      - postgres-compose-network
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "poc"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - pg
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
